// Blob Storage for the H-1B pipeline.
//
//   raw/      the nine DOL .xlsx workbooks, as downloaded
//   curated/  Parquet written by the ETL job
//
// Free-tier notes (plan §7): 5 GB LRS hot is free for the first 12 months, and
// measured usage is 175 MB of Parquet. The storage account itself costs nothing
// to exist — you pay for what is stored and for transactions.

@description('Azure region. Defaults to the resource group\'s location.')
param location string

@description('Short project prefix. Storage account names allow only lowercase letters and digits, so this cannot contain the hyphen used elsewhere (h1b-web, h1b-etl).')
@minLength(2)
@maxLength(8)
param namePrefix string

@description('Days before a blob under raw/ is deleted by the lifecycle policy.')
@minValue(1)
param rawRetentionDays int

// Storage account names are globally unique across all of Azure, 3-24 chars,
// lowercase alphanumeric only. uniqueString() is deterministic per resource
// group, so redeploying yields the same name rather than orphaning the old one.
// 'st' (2) + prefix (<=8) + uniqueString (13) stays inside 24.
var storageAccountName = 'st${namePrefix}${uniqueString(resourceGroup().id)}'

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageAccountName
  location: location
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    // ADLS Gen2 hierarchical namespace is off on purpose: nothing here needs
    // directory semantics, and it complicates plain SDK blob access.
    isHnsEnabled: false
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
    // The ETL job and the web app both authenticate with managed identity, so
    // no blob ever needs to be publicly readable.
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
  }
}

// Soft delete stays off. The raw .xlsx are re-downloadable from DOL and the
// curated Parquet is regenerated by re-running the ETL, so retaining deleted
// blobs would only consume the 5 GB free allowance. Declared explicitly rather
// than left to the server default, for the `what-if` reason above.
resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
  properties: {
    deleteRetentionPolicy: {
      enabled: false
      allowPermanentDelete: false
    }
  }
}

// defaultEncryptionScope and denyEncryptionScopeOverride are declared even
// though both are Azure's defaults. Omitting them leaves the server populating
// values the template does not mention, and `what-if` then reports them as
// removals on every subsequent run — 3 phantom modifications that never apply.
// Step 3's acceptance criterion is a clean second run, and Step 11 deploys from
// CI, where a permanently dirty diff hides real drift.
resource rawContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: 'raw'
  properties: {
    publicAccess: 'None'
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
  }
}

resource curatedContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: 'curated'
  properties: {
    publicAccess: 'None'
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
  }
}

// Deletes blobs under raw/ after rawRetentionDays. The source .xlsx files are
// re-downloadable from DOL, so keeping them indefinitely buys nothing and only
// eats into the 5 GB free allowance.
//
// prefixMatch is matched against the full blob path *including* the container
// name, so 'raw/' scopes this to the raw container and leaves curated/ alone.
resource lifecyclePolicy 'Microsoft.Storage/storageAccounts/managementPolicies@2023-05-01' = {
  parent: storageAccount
  name: 'default'
  properties: {
    policy: {
      rules: [
        {
          name: 'delete-raw-after-retention'
          enabled: true
          type: 'Lifecycle'
          definition: {
            filters: {
              blobTypes: [
                'blockBlob'
              ]
              prefixMatch: [
                'raw/'
              ]
            }
            actions: {
              baseBlob: {
                delete: {
                  daysAfterModificationGreaterThan: rawRetentionDays
                }
              }
            }
          }
        }
      ]
    }
  }
}

output storageAccountName string = storageAccount.name
output blobEndpoint string = storageAccount.properties.primaryEndpoints.blob
output storageAccountId string = storageAccount.id
